"""add case info 

Revision ID: 0081be560f36
Revises: 309f3efd21c1
Create Date: 2025-12-10 12:19:53.368523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0081be560f36'
down_revision: Union[str, Sequence[str], None] = '309f3efd21c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('actual_label', sa.JSON(), nullable=True, comment='실제 형량'))
    op.add_column('cases', sa.Column('actual_rule', sa.JSON(), nullable=True, comment='형량 적용 규칙'))
    op.add_column('cases', sa.Column('actual_reason', sa.Text(), nullable=True, comment='실제 양형 사유'))
    op.drop_column('cases', 'actual_sentence')
    op.drop_column('cases', 'actual_reasoning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('actual_reasoning', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='실제 양형 사유'))
    op.add_column('cases', sa.Column('actual_sentence', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='실제 형량'))
    op.drop_column('cases', 'actual_reason')
    op.drop_column('cases', 'actual_rule')
    op.drop_column('cases', 'actual_label')
    # ### end Alembic commands ###
