"""title nullable

Revision ID: 1b86946dedf2
Revises: 3af632604bf3
Create Date: 2025-12-10 11:49:12.626218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b86946dedf2'
down_revision: Union[str, Sequence[str], None] = '3af632604bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_comment='사건 제목')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_comment='사건 제목')
    # ### end Alembic commands ###
