"""conversation edit

Revision ID: 2dabadb58ea6
Revises: 9bd4f5a5beb9
Create Date: 2025-12-16 21:37:37.719595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dabadb58ea6'
down_revision: Union[str, Sequence[str], None] = '9bd4f5a5beb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'facts_temp')
    op.add_column('conversations', sa.Column('turn_count', sa.Integer(), nullable=False, comment='전체 턴 수 (정렬용)'))
    op.add_column('conversations', sa.Column('phase', sa.String(length=50), nullable=False, comment='진행 단계 (briefing, debate, judgment, etc.)'))
    op.add_column('conversations', sa.Column('speaker', sa.String(length=50), nullable=False, comment='발화자 (prosecutor, defense, judge, etc.)'))
    op.add_column('conversations', sa.Column('content', sa.Text(), nullable=False, comment='순수 발화 내용 (JSON 아님)'))
    op.add_column('conversations', sa.Column('metadata_json', sa.JSON(), nullable=True, comment='메타데이터 (emotion, references, role_detail 등)'))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성 일시'))
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='PK',
               existing_comment='대화 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='세션 ID',
               existing_comment='세션 식별자')
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='관련 사건 ID (Optional)',
               existing_comment='관련 사건 ID')
    op.create_index(op.f('ix_conversations_phase'), 'conversations', ['phase'], unique=False)
    op.create_index(op.f('ix_conversations_speaker'), 'conversations', ['speaker'], unique=False)
    op.create_index(op.f('ix_conversations_turn_count'), 'conversations', ['turn_count'], unique=False)
    op.drop_column('conversations', 'message')
    op.drop_column('conversations', 'agent_role')
    op.drop_column('conversations', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='발화 시각'))
    op.add_column('conversations', sa.Column('agent_role', postgresql.ENUM('PROSECUTOR', 'DEFENSE', 'LEGAL_ADVISOR', 'USER_JUDGE', name='agentrole'), autoincrement=False, nullable=False, comment='발화자 역할'))
    op.add_column('conversations', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False, comment='메시지 내용'))
    op.drop_index(op.f('ix_conversations_turn_count'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_speaker'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_phase'), table_name='conversations')
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='관련 사건 ID',
               existing_comment='관련 사건 ID (Optional)')
    op.alter_column('conversations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='세션 식별자',
               existing_comment='세션 ID')
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='대화 ID',
               existing_comment='PK',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'metadata_json')
    op.drop_column('conversations', 'content')
    op.drop_column('conversations', 'speaker')
    op.drop_column('conversations', 'phase')
    op.drop_column('conversations', 'turn_count')
    op.add_column('cases', sa.Column('facts_temp', sa.TEXT(), autoincrement=False, nullable=True, comment='(삭제예정) facts 원문'))
    # ### end Alembic commands ###
