"""add case info 

Revision ID: 309f3efd21c1
Revises: 1b86946dedf2
Create Date: 2025-12-10 12:10:05.109837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309f3efd21c1'
down_revision: Union[str, Sequence[str], None] = '1b86946dedf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('casetype', sa.String(length=50), nullable=True, comment='민사/형사'))
    op.add_column('cases', sa.Column('casename', sa.String(length=50), nullable=True, comment='범죄 유형'))
    op.drop_column('cases', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='범죄 유형'))
    op.drop_column('cases', 'casename')
    op.drop_column('cases', 'casetype')
    # ### end Alembic commands ###
