"""Initial migration

Revision ID: 3af632604bf3
Revises: 51b1206a3f5c
Create Date: 2025-12-10 11:08:21.304335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af632604bf3'
down_revision: Union[str, Sequence[str], None] = '51b1206a3f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'id',
               existing_type=sa.INTEGER(),
               comment='사건 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cases', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               comment='사건 번호',
               existing_nullable=True)
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='사건 제목',
               existing_nullable=False)
    op.alter_column('cases', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='범죄 유형',
               existing_nullable=True)
    op.alter_column('cases', 'description',
               existing_type=sa.TEXT(),
               comment='사건 개요',
               existing_nullable=True)
    op.alter_column('cases', 'facts',
               existing_type=sa.TEXT(),
               comment='사실관계',
               existing_nullable=True)
    op.alter_column('cases', 'actual_sentence',
               existing_type=sa.VARCHAR(length=200),
               comment='실제 형량',
               existing_nullable=True)
    op.alter_column('cases', 'actual_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='실제 양형 사유',
               existing_nullable=True)
    op.alter_column('cases', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment='데이터 출처',
               existing_nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성 일시',
               existing_nullable=True)
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정 일시',
               existing_nullable=True)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='대화 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               comment='관련 사건 ID',
               existing_nullable=False)
    op.alter_column('conversations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='세션 식별자',
               existing_nullable=True)
    op.alter_column('conversations', 'agent_role',
               existing_type=postgresql.ENUM('PROSECUTOR', 'DEFENSE', 'LEGAL_ADVISOR', 'USER_JUDGE', name='agentrole'),
               comment='발화자 역할',
               existing_nullable=False)
    op.alter_column('conversations', 'message',
               existing_type=sa.TEXT(),
               comment='메시지 내용',
               existing_nullable=False)
    op.alter_column('conversations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='발화 시각',
               existing_nullable=True)
    op.alter_column('judgments', 'id',
               existing_type=sa.INTEGER(),
               comment='판결 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('judgments', 'case_id',
               existing_type=sa.INTEGER(),
               comment='관련 사건 ID',
               existing_nullable=False)
    op.alter_column('judgments', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='세션 식별자',
               existing_nullable=True)
    op.alter_column('judgments', 'user_sentence',
               existing_type=sa.VARCHAR(length=200),
               comment='유저가 선고한 형량',
               existing_nullable=True)
    op.alter_column('judgments', 'user_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='유저의 양형 사유',
               existing_nullable=True)
    op.alter_column('judgments', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='실제 판결과의 유사도 점수',
               existing_nullable=True)
    op.alter_column('judgments', 'difference_analysis',
               existing_type=sa.TEXT(),
               comment='실제 판결과의 차이점 분석',
               existing_nullable=True)
    op.alter_column('judgments', 'feedback',
               existing_type=sa.TEXT(),
               comment='AI 판사의 피드백',
               existing_nullable=True)
    op.alter_column('judgments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='판결 생성 일시',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('judgments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='판결 생성 일시',
               existing_nullable=True)
    op.alter_column('judgments', 'feedback',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI 판사의 피드백',
               existing_nullable=True)
    op.alter_column('judgments', 'difference_analysis',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='실제 판결과의 차이점 분석',
               existing_nullable=True)
    op.alter_column('judgments', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='실제 판결과의 유사도 점수',
               existing_nullable=True)
    op.alter_column('judgments', 'user_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='유저의 양형 사유',
               existing_nullable=True)
    op.alter_column('judgments', 'user_sentence',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='유저가 선고한 형량',
               existing_nullable=True)
    op.alter_column('judgments', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='세션 식별자',
               existing_nullable=True)
    op.alter_column('judgments', 'case_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='관련 사건 ID',
               existing_nullable=False)
    op.alter_column('judgments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='판결 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='발화 시각',
               existing_nullable=True)
    op.alter_column('conversations', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='메시지 내용',
               existing_nullable=False)
    op.alter_column('conversations', 'agent_role',
               existing_type=postgresql.ENUM('PROSECUTOR', 'DEFENSE', 'LEGAL_ADVISOR', 'USER_JUDGE', name='agentrole'),
               comment=None,
               existing_comment='발화자 역할',
               existing_nullable=False)
    op.alter_column('conversations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='세션 식별자',
               existing_nullable=True)
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='관련 사건 ID',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='대화 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정 일시',
               existing_nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성 일시',
               existing_nullable=True)
    op.alter_column('cases', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='데이터 출처',
               existing_nullable=True)
    op.alter_column('cases', 'actual_reasoning',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='실제 양형 사유',
               existing_nullable=True)
    op.alter_column('cases', 'actual_sentence',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='실제 형량',
               existing_nullable=True)
    op.alter_column('cases', 'facts',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='사실관계',
               existing_nullable=True)
    op.alter_column('cases', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='사건 개요',
               existing_nullable=True)
    op.alter_column('cases', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='범죄 유형',
               existing_nullable=True)
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='사건 제목',
               existing_nullable=False)
    op.alter_column('cases', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='사건 번호',
               existing_nullable=True)
    op.alter_column('cases', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사건 ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
