"""relax case_id fk

Revision ID: 7c3a71824fa2
Revises: 2dabadb58ea6
Create Date: 2025-12-16 21:49:09.899824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3a71824fa2'
down_revision: Union[str, Sequence[str], None] = '2dabadb58ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               comment='관련 사건 ID (Optional, No FK constraint)',
               existing_comment='관련 사건 ID (Optional)',
               existing_nullable=True)
    op.drop_constraint(op.f('conversations_case_id_fkey'), 'conversations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('conversations_case_id_fkey'), 'conversations', 'cases', ['case_id'], ['id'])
    op.alter_column('conversations', 'case_id',
               existing_type=sa.INTEGER(),
               comment='관련 사건 ID (Optional)',
               existing_comment='관련 사건 ID (Optional, No FK constraint)',
               existing_nullable=True)
    # ### end Alembic commands ###
