"""add metadata 

Revision ID: 9bd4f5a5beb9
Revises: 0081be560f36
Create Date: 2025-12-10 15:33:56.933821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd4f5a5beb9'
down_revision: Union[str, Sequence[str], None] = '0081be560f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_metadata', sa.JSON(), nullable=True, comment='메타데이터'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'case_metadata')
    # ### end Alembic commands ###
