"""Centralized prompt management for BupBlessYou agents"""

from .prosecutor_prompts import PROSECUTOR_SYSTEM_PROMPT, PROSECUTOR_HUMAN_TEMPLATE
from .defense_prompts import DEFENSE_SYSTEM_PROMPT, DEFENSE_HUMAN_TEMPLATE
from .legal_advisor_prompts import LEGAL_ADVISOR_SYSTEM_PROMPT, LEGAL_ADVISOR_HUMAN_TEMPLATE
from .router_prompts import ROUTER_SYSTEM_PROMPT, ROUTER_HUMAN_TEMPLATE
from .judgment_prompts import JUDGMENT_ANALYZER_SYSTEM_PROMPT, JUDGMENT_ANALYZER_HUMAN_TEMPLATE

__all__ = [
    "PROSECUTOR_SYSTEM_PROMPT",
    "PROSECUTOR_HUMAN_TEMPLATE",
    "DEFENSE_SYSTEM_PROMPT",
    "DEFENSE_HUMAN_TEMPLATE",
    "LEGAL_ADVISOR_SYSTEM_PROMPT",
    "LEGAL_ADVISOR_HUMAN_TEMPLATE",
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_HUMAN_TEMPLATE",
    "JUDGMENT_ANALYZER_SYSTEM_PROMPT",
    "JUDGMENT_ANALYZER_HUMAN_TEMPLATE",
]
